import React from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { Underline } from "@tiptap/extension-underline";
import { Subscript } from "@tiptap/extension-subscript";
import { Superscript } from "@tiptap/extension-superscript";
import { TextAlign } from "@tiptap/extension-text-align";
import { Link } from "@tiptap/extension-link";
import { Table } from "@tiptap/extension-table";
import { TableRow } from "@tiptap/extension-table-row";
import { TableCell } from "@tiptap/extension-table-cell";
import { TableHeader } from "@tiptap/extension-table-header";
import ImageResize from "tiptap-extension-resize-image";
import MathExtension from "@aarkue/tiptap-math-extension";
import "katex/dist/katex.min.css";
import { TextStyle } from "@tiptap/extension-text-style";
import { FontSize } from "./extensions/fontSizeExtension";

interface RichTextDisplayProps {
  content: string;
  className?: string;
}

/**
 * A read-only component that perfectly renders HTML content generated by the Tiptap editor,
 * including complex nodes like KaTeX math formulas, tables, and text alignments.
 */
const RichTextDisplay: React.FC<RichTextDisplayProps> = ({
  content,
  className = "",
}) => {
  const editor = useEditor({
    extensions: [
      StarterKit,
      Underline,
      Subscript,
      Superscript,
      TextAlign.configure({ types: ["heading", "paragraph"] }),
      Link.configure({ openOnClick: true }),
      Table.configure({ resizable: true }),
      TableRow,
      TableHeader,
      TableCell,
      ImageResize,
      MathExtension.configure({ evaluation: false }),
      TextStyle,
      FontSize,
    ],
    content: content,
    editable: false,
    editorProps: {
      attributes: {
        class: `prose dark:prose-invert max-w-none focus:outline-none text-[11pt] prose-p:text-[11pt] prose-h1:text-[24pt] prose-h2:text-[18pt] prose-h3:text-[14pt] prose-img:my-0 ${className}`,
      },
    },
  });

  // Sync content from props to editor when it changes from outside
  React.useEffect(() => {
    if (editor && content !== editor.getHTML()) {
      editor.commands.setContent(content, { emitUpdate: false });
    }
  }, [editor, content]);

  if (!editor) {
    return null;
  }

  return (
    <EditorContent
      editor={editor}
      className={className.includes("inline") ? "inline" : ""}
    />
  );
};

export default RichTextDisplay;
