export interface AlgorithmicTemplate {
  id: string;
  name: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  tag: string;
  code: string;
}

export const languageTemplates: Record<string, AlgorithmicTemplate[]> = {
  javascript: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "function fibonacci(n) {\n  // Your solution here\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "function isPalindrome(str) {\n  // Your solution here\n}",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "function twoSum(nums, target) {\n  // Your solution here\n}",
    },
    {
      id: "binarysearch",
      name: "Binary Search",
      description: "Find the index of a target value in a sorted array",
      difficulty: "beginner",
      tag: "Search",
      code: "function binarySearch(arr, target) {\n  // Your solution here\n}",
    },
    {
      id: "lrucache",
      name: "LRU Cache",
      description: "Implement a Least Recently Used (LRU) cache",
      difficulty: "advanced",
      tag: "Design",
      code: "class LRUCache {\n  constructor(capacity) {\n    // Your solution here\n  }\n  get(key) {\n    // Your solution here\n  }\n  put(key, value) {\n    // Your solution here\n  }\n}",
    },
  ],
  python: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "def fibonacci(n):\n    # Your solution here\n    pass",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "def is_palindrome(s):\n    # Your solution here\n    pass",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "def two_sum(nums, target):\n    # Your solution here\n    pass",
    },
    {
      id: "binarysearch",
      name: "Binary Search",
      description: "Find the index of a target value in a sorted array",
      difficulty: "beginner",
      tag: "Search",
      code: "def binary_search(arr, target):\n    # Your solution here\n    pass",
    },
    {
      id: "lrucache",
      name: "LRU Cache",
      description: "Implement a Least Recently Used (LRU) cache",
      difficulty: "advanced",
      tag: "Design",
      code: "class LRUCache:\n    def __init__(self, capacity: int):\n        pass\n\n    def get(self, key: int) -> int:\n        pass\n\n    def put(self, key: int, value: int) -> None:\n        pass",
    },
  ],
  java: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "public class Solution {\n    public int fibonacci(int n) {\n        // Your solution here\n        return 0;\n    }\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "public class Solution {\n    public boolean isPalindrome(String str) {\n        // Your solution here\n        return false;\n    }\n}",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "public class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        // Your solution here\n        return new int[]{};\n    }\n}",
    },
    {
      id: "binarysearch",
      name: "Binary Search",
      description: "Find the index of a target value in a sorted array",
      difficulty: "beginner",
      tag: "Search",
      code: "public class Solution {\n    public int binarySearch(int[] arr, int target) {\n        // Your solution here\n        return -1;\n    }\n}",
    },
  ],
  cpp: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "#include <iostream>\nusing namespace std;\n\nclass Solution {\npublic:\n    int fibonacci(int n) {\n        // Your solution here\n        return 0;\n    }\n};",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "#include <iostream>\n#include <string>\nusing namespace std;\n\nclass Solution {\npublic:\n    bool isPalindrome(string s) {\n        // Your solution here\n        return false;\n    }\n};",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        // Your solution here\n        return {};\n    }\n};",
    },
    {
      id: "binarysearch",
      name: "Binary Search",
      description: "Find the index of a target value in a sorted array",
      difficulty: "beginner",
      tag: "Search",
      code: "#include <vector>\nusing namespace std;\n\nclass Solution {\npublic:\n    int binarySearch(vector<int>& arr, int target) {\n        // Your solution here\n        return -1;\n    }\n};",
    },
  ],
  c: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "#include <stdio.h>\n\nint fibonacci(int n) {\n    // Your solution here\n    return 0;\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "#include <stdio.h>\n#include <stdbool.h>\n\nbool isPalindrome(const char* str) {\n    // Your solution here\n    return false;\n}",
    },
  ],
  go: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "package main\n\nfunc fibonacci(n int) int {\n\t// Your solution here\n\treturn 0\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "package main\n\nfunc isPalindrome(s string) bool {\n\t// Your solution here\n\treturn false\n}",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "package main\n\nfunc twoSum(nums []int, target int) []int {\n\t// Your solution here\n\treturn nil\n}",
    },
  ],
  rust: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "pub fn fibonacci(n: i32) -> i32 {\n    // Your solution here\n    0\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "pub fn is_palindrome(s: String) -> bool {\n    // Your solution here\n    false\n}",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> {\n    // Your solution here\n    vec![]\n}",
    },
  ],
  php: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "<?php\n\nclass Solution {\n    function fibonacci($n) {\n        // Your solution here\n        return 0;\n    }\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "<?php\n\nclass Solution {\n    function isPalindrome($s) {\n        // Your solution here\n        return false;\n    }\n}",
    },
  ],
  ruby: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "def fibonacci(n)\n  # Your solution here\n  0\nend",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "def is_palindrome(s)\n  # Your solution here\n  false\nend",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "def two_sum(nums, target)\n  # Your solution here\n  []\nend",
    },
  ],
  csharp: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "public class Solution {\n    public int Fibonacci(int n) {\n        // Your solution here\n        return 0;\n    }\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "public class Solution {\n    public bool IsPalindrome(string s) {\n        // Your solution here\n        return false;\n    }\n}",
    },
    {
      id: "twosum",
      name: "Two Sum",
      description: "Find indices of the two numbers that sum to target",
      difficulty: "intermediate",
      tag: "Array",
      code: "public class Solution {\n    public int[] TwoSum(int[] nums, int target) {\n        // Your solution here\n        return new int[0];\n    }\n}",
    },
  ],
  swift: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "class Solution {\n    func fibonacci(_ n: Int) -> Int {\n        // Your solution here\n        return 0\n    }\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "class Solution {\n    func isPalindrome(_ s: String) -> Bool {\n        // Your solution here\n        return false\n    }\n}",
    },
  ],
  kotlin: [
    {
      id: "fibonacci",
      name: "Fibonacci Sequence",
      description: "Calculate the nth Fibonacci number optimally",
      difficulty: "beginner",
      tag: "Math",
      code: "class Solution {\n    fun fibonacci(n: Int): Int {\n        // Your solution here\n        return 0\n    }\n}",
    },
    {
      id: "palindrome",
      name: "Palindrome Check",
      description: "Determine if a given string is a palindrome",
      difficulty: "beginner",
      tag: "String",
      code: "class Solution {\n    fun isPalindrome(s: String): Boolean {\n        // Your solution here\n        return false\n    }\n}",
    },
  ],
};
